<a href="https://colab.research.google.com/github/smomtahe/NLP_Tranformer_BERT/blob/main/Transformer_BERT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install transformers

In [2]:
from transformers import pipeline
classifier = pipeline('sentiment-analysis') # an example of pipeline
# pipeline : call a pretrained model (BERT or GPT or ... ) and its tokenizer are downloded
# tokenizer : preprocess the text for the model -> prediction
# pipeline groups all of that together and post-process the predictions to make them readable

No model was supplied, defaulted to distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:88: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

In [ ]:
classifier('I am a :) person')

[{'label': 'POSITIVE', 'score': 0.9950520396232605}]

In [ ]:
# list of sentences - fed to th emodel as a batch - return a list of dictionaries
results =classifier(["I have a good mother :)", "I really love my mom.","i have a difficult exam","I am sad with hope )"])
results

[{'label': 'POSITIVE', 'score': 0.9997528195381165},
 {'label': 'POSITIVE', 'score': 0.9998571872711182},
 {'label': 'NEGATIVE', 'score': 0.9981840252876282},
 {'label': 'NEGATIVE', 'score': 0.5955883860588074}]

In [ ]:
for result in results:
  print(f"label:{result['label']}, score:{round(result['score'],4)}")

label:POSITIVE, score:0.9998
label:POSITIVE, score:0.9999
label:NEGATIVE, score:0.9982
label:NEGATIVE, score:0.5956


In [ ]:
# the model downloaded for this pieline is called : distilbirt-base-uncased-finetuned-sst-2-english
# DistilBERT architecture : fine tuned on a dataset : SST-2 for sentiment analysis
# use another model : French data - text-classification

In [5]:
classifier=pipeline('sentiment-analysis', model="nlptown/bert-base-multilingual-uncased-sentiment")

config.json:   0%|          | 0.00/953 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/669M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/39.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/872k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

In [10]:
classifier("La nourriture est mauvise")  # very poitive 5 star

[{'label': '2 stars', 'score': 0.44696471095085144}]

In [11]:
classifier("La comida as mala ")  # Spanish

[{'label': '1 star', 'score': 0.3616013824939728}]

In [12]:
from transformers import AutoTokenizer, TFAutoModelForSequenceClassification

In [13]:
model_name="nlptown/bert-base-multilingual-uncased-sentiment"
# This model only exists in PyTorch so we use the 'from_pt' flag to import this model to TensorFlow
model=TFAutoModelForSequenceClassification.from_pretrained(model_name,from_pt=True)
tokenizer=AutoTokenizer.from_pretrained(model_name)
classifier=pipeline('sentiment-analysis', model=model,tokenizer=tokenizer )

All PyTorch model weights were used when initializing TFBertForSequenceClassification.

All the weights of TFBertForSequenceClassification were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForSequenceClassification for predictions without further training.


In [14]:
classifier("I am a good girl") # greater than 3 is positive

[{'label': '4 stars', 'score': 0.41006219387054443}]

In [15]:
# Pretrained models
from transformers import AutoTokenizer, TFAutoModelForSequenceClassification
model_name="distilbert-base-uncased-finetuned-sst-2-english"
tf_model=TFAutoModelForSequenceClassification.from_pretrained(model_name)
tokenizer=AutoTokenizer.from_pretrained(model_name)


All PyTorch model weights were used when initializing TFDistilBertForSequenceClassification.

All the weights of TFDistilBertForSequenceClassification were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertForSequenceClassification for predictions without further training.


In [17]:
inputs=tokenizer(" we are very happy :)")
print(inputs)

{'input_ids': [101, 2057, 2024, 2200, 3407, 1024, 1007, 102], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1]}


In [22]:
tf_batch=tokenizer(["we are very happy :) ","we hope you dont have "], padding=True, truncation=True,max_length=512,return_tensors="tf")
tf_batch
# padding make all the sentences equal

{'input_ids': <tf.Tensor: shape=(2, 8), dtype=int32, numpy=
array([[ 101, 2057, 2024, 2200, 3407, 1024, 1007,  102],
       [ 101, 2057, 3246, 2017, 2123, 2102, 2031,  102]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(2, 8), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)>}

In [24]:
for key, value in tf_batch.items():
  print(f"{key}:{value.numpy().tolist()}")

input_ids:[[101, 2057, 2024, 2200, 3407, 1024, 1007, 102], [101, 2057, 3246, 2017, 2123, 2102, 2031, 102]]
attention_mask:[[1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1]]
